---
title: "R and RStudio (ICO - Utrecht - 2024)"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    theme: 
        version: 4
        bootswatch: flatly
    vertical_layout: scroll
---


```{r setup, include=FALSE}
library(flexdashboard)
```

# Intro {.sidebar}

This site bundles all the material used for the workshop [R and RStudio]{style="color: #EB6864"}. 

---

Instructors: 


 - <a href="https://sdemaeyer.quarto.pub/" target="blank">Sven De Maeyer</a> 
 - <a href="https://www.uantwerpen.be/nl/personeel/tine-vandaal/" target="blank">Tine van Daal</a>
 
---

All materials for the course can be downloaded via <a href="https://github.com/Sdemaeyer2/abar_Turku2024" target="_blank">the github page </a>. 

---

Questions or feedback, do not hesitate to contact us:

sven.demaeyer@uantwerpen.be
tine.vandaal@uantwerpen.be


---

# Quick Overview

## Column 1

### Outline

Handling datasets is a skill that is central to many research areas. Managing, analysing and displaying data are challenging tasks that require learning specific software. In this workshop, you will be introduced to R and RStudio, one of the most versatile language and software environment for data analysis. The fact that this software is open-source makes it one of the most used statistical programming languages in scientific research at the moment. The workshop will teach you ‘hands-on’ to take your first steps in R and RStudio and prepare you to work with them in the professional research context.

Description of session contents

The training consists of four parts:

- R: You get to know the program R and its language by means of a number of examples. You practice with data management and datasets: reading data from other software (MS Excel, SPSS, …), changing/re-coding variables and other data management steps using the intuitive ‘tidyverse’ method. This will be all approached by making use of the power of creating RStudio projects.
- Graphs: You will learn to use R as a powerful tool to create different graphs via the package ‘ggplot2’.
- R Markdown/Quarto: You will learn to create reproducible documents (such as html reports, word docs and slides) so that you can integrate content (the explanations of the analyses and results) analyses (the way in which the results are produced (read: the underlying code) as well as the results themselves, nicely and easily, into one overall document.
- Basic analyses: finally, you will learn how to perform some of the most common analyses in R (correlations; t-test; linear regression analyses).

In the course we will schedule some time to work with your own research data (or with a dataset of us) so that you can immediately transfer what is learned to your owns projects.

## Column 2

### Rooms

| When?  | Where    |
|:--------|:-------|
| Tuesday July 2 (9:00 am - 11:00 am) | 
| Wednesday July 3 10 (10:00 am - 12:00 am) | 
| Thursday July 4  (10:00 am - 12:00 am) | 

Vergadercentrum Vredenburg, Vredenburg 19 Utrecht

# Part 1

## Column 1

### Outline

In the first part, we will introduce the basic rationale behind Bayesian statistics. We start by explaining the three key components of a Bayesian model: the prior, the likelihood, and the posterior. 

Then, we switch to the estimation of parameters by first introducing the basic idea of grid approximation and then outlining the basic idea of MCMC sampling.

At the end of the session we introduce `brms` and learn how to estimate a simple regression model with `brms` and just use the `summary()` and `plot()` functions to get insight in the model results.

### Materials

#### Slides

The htlm-version of the slides for this first part can be found <a href="Presentations/Part1/Slides_Part1.html" target="blank">here</a>

#### Data

For this first part, we use a straightforward dataset on predicting racetimes for a marathon. The data can be downloaded <a href="Data/MarathonData.RData" target="blank"> here </a> (right-click to save as). 

## Column 2

### References and resources

Data comes from <a href="https://www.kaggle.com/datasets/girardi69/marathon-time-predictions?resource=download" target="blank">Kaggle</a>

Paul Bürkner’s presentation available on YouTube:<a href="https://www.youtube.com/watch?v=FRs1iribZME" target="blank"> click here</a>

Interactive tool demonstrating MCMC sampling: 
<a href="https://chi-feng.github.io/mcmc-demo/app.html#HamiltonianMC,standard" target="blank"> click here </a>

`brms` homepage: <a href="https://paul-buerkner.github.io/brms/" target="blank"> click here </a>


# Part 2

## Column 1

### Outline

The second part of this workshop taps into the concept of the priors. Prior probability distributions are of crucial importance in Bayesian models. `brms` will set default priors for all the parameters in your model. Nevertheless, as a researcher it is important to understand what your piors actually mean. Therefore, just using the default priors without a critical understanding of these priors is sub-optimal. We will discuss and exercise how to think about priors and how to use them in `brms`.

#### Slides

The htlm-version of the slides for this part can be found <a href="Presentations/Part2/Slides_Part2.html" target="blank">here</a>

#### Data

For this part, we again use the straightforward dataset on predicting racetimes for a marathon. The data can be downloaded <a href="Data/MarathonData.RData" target="blank"> here </a> (right-click to save as). 

# Part 3

## Column 1

### Outline

In this part of the workshop we go one step further. We will first shortly introduce the idea of *leave-one-out cross-validation* which can be used to compare alternative models. Next we will estimate some *Bayesian Mixed Effects Models* and delve into the endeavour to think about the different priors. We will consider alternative priors for both the fixed and random effect parameters in the model. Using prior predictive checking we will consider the impact of these priors. Finally, we will also introduce the concept of *posterior predictive checking* to evaluate our model. 

#### Slides

The htlm-version of the slides for this first part can be found <a href="Presentations/Part3/Slides_Part3.html" target="blank">here</a>

#### Data

For this first part, we used a dataset on the effect of a writing intervention. The data can be downloaded <a href="Data/WritingData.RData" target="blank"> here </a> (right-click to save as). 


## Column 2

### References and resources


# Part 4

## Column 1

### Outline

This part of the workshop is about interpreting and reporting the results of our models. Here we demonstrate different ways to make sense of the information in our posterior probability distributions for our parameters. First, we will show how different packages in `R` can be used to visually explore the posterior probability distributions. Next, we focus on how to numerically summarize the information in the posterior probability distribution in order to support our reporting on the results. 

#### Slides

The htlm-version of the slides for this first part can be found <a href="Presentations/Part4/Slides_Part4.html" target="blank">here</a>

#### Data

For this first part, we used a dataset on the effect of a writing intervention. The data can be downloaded <a href="Data/WritingData.RData" target="blank"> here </a> (right-click to save as). 

#### R scripts

A powerful way to visualize the effects of (mixed effects) regression models, is to plot <i>Hypothetical Outcome Plots</i>. These type of plots need a considerable amount of coding. Therefore, we provide two R-scripts that can be used as a starting point to plot your own results:

- <a href="R_code/HOP_Script.R" target="blank"> HOP_Script.R </a>

- <a href="R_code/HOP_MixedEffects_Script.R" target="blank"> HOP_MixedEffects_Script.R </a>

## Column 2

### References and resources

More on the `bayesplot` package: <a href="https://mc-stan.org/bayesplot/" target="blank"> https://mc-stan.org/bayesplot/ </a>

More on the `ggdist` package: <a href="https://mjskay.github.io/ggdist/reference/index.html" target="blank"> https://mjskay.github.io/ggdist/reference/index.html </a>

Papers on the use of quantile dotplots: 

- <a href="https://dl.acm.org/doi/10.1145/2858036.2858558" target="blank"> https://dl.acm.org/doi/10.1145/2858036.2858558 </a>

- <a href="https://www.mjskay.com/papers/chi2018-uncertain-bus-decisions.pdf" target="blank"> https://www.mjskay.com/papers/chi2018-uncertain-bus-decisions.pdf </a>


# Integrated exercise

## Column 1

### Outline

In this final part, it is your turn! We have created an integrated exercise. 

On the following page you can find an html file with the tasks for this exercise: <a href="Integrated_exercise/Exercise.html" target="blank">click here</a>

The dataset for this exercise can be downloaded here: <a href="Integrated_exercise/Subtitles.RData" target="blank">Subtitles.RData</a>

If you are stuck while making this exercise, you can consult an example response <a href="Integrated_exercise/Exercise_response.html" target="blank">here </a>

## Column 2

### References and resources

The data for the exercise is a simulated dataset based on the following study:

Frumuselu, Anca Daniela, Sven De Maeyer, Vincent Donche, and María del Mar Gutiérrez Colon Plana. 2015. “Television Series Inside the EFL Classroom: Bridging the Gap Between Teaching and Learning Informal Language Through Subtitles.” Linguistics and Education 32 (December): 107–17. https://doi.org/10.1016/j.linged.2015.10.001.

# WAMBS Template

## Column 1

### Info

During the course we shorlty introduced the WAMBS (when to Worry and how to Avoid the Misuse of Bayesian Statistics) check-list as a tool to structure your thinking and checking of your Bayesian model(s). 

To see an example of this WAMBS checklist applied to the final model on the Marathon Data click <a href="WAMBS_template/WAMBS_workflow_MarathonData.html" target="blank">here</a>.

The Quarto document to make this report can be found <a href="WAMBS_template/WAMBS_workflow_MarathonData.qmd" target="blank">here</a> (right-click to save).

If you want to render the Quarto document and have the references in there, you also need to download the `references.bib` file and store it in the same folder as the Quarto document. The references file can be downloaded <a href="WAMBS_template/references.bib" target="blank">here</a> (right-click to save).


## Column 2

### References and resources

Depaoli, S., & Van de Schoot, R. (2017). Improving transparency and replication in Bayesian statistics: The WAMBS-Checklist. Psychological methods, 22(2), 240.

Van de Schoot, R., Veen, D., Smeets, L., Winter, S. D., & Depaoli, S. (2020). A tutorial on using the WAMBS checklist to avoid the misuse of Bayesian statistics. Small Sample Size Solutions: A Guide for Applied Researchers and Practitioners; van de Schoot, R., Miocevic, M., Eds, 30-49.

# Links

## Column 1

### Reading tips

Many books are written that discuss Bayesian modelling. Here you can find two books that I would suggest for learning more about Bayesian analyses.

A first book is the book by <b>Ben Lambert</b>: <b>"A Student's Guide to Bayesian Statistics"</b>. This book is great if you want to learn more about the statistical theory behind Bayesian analyses and MCMC sampling. He succeeds in explaining these topics in a thorough conceptual way, without you getting lost in the mathematics and formulas. For me, this book was of great value!

A big hit these days is the book by <b> Richard McElreath</b>: <b>"Statistical Rethinking. A Bayesian Course with examples in R and Stan" </b>. In this course, Richard McElreath introduces statistical reasoning from scratch, integrating three key components for good statistical thinking: DAGs, Bayesian statistics, and multi-level models. So, this book is more than solely a book about Bayesian models. The lectures of Richard McElreath based on this book can be found for free on YouTube. 

### Some free online books `r fontawesome::fa("book")`

-   John Kruschke's book <b>Doing Bayesian Data Analyses: a tutorial with R, Jags, and Stan </b>:

<a href="https://nyu-cdsc.github.io/learningr/assets/kruschke_bayesian_in_R.pdf" target="blank">https://nyu-cdsc.github.io/learningr/assets/kruschke_bayesian_in_R.pdf</a>

-   Bayes Rules!:

<a href="https://www.bayesrulesbook.com/" target="blank">https://www.bayesrulesbook.com/</a>

-   Or this book:

<a href="https://vasishth.github.io/bayescogsci/book/"> https://vasishth.github.io/bayescogsci/book/ </a>

## Column 2

### THE Podcast `r fontawesome::fa("podcast")`

If you like running - like I do - this could be a great companion on your run! In this podcast different guests from different backgrounds discuss the power and reasoning behind Bayesian analyses and how Bayesian statistics are used in their field from Astronomy, over Psychology to Sports Analyses (and many more).

<a href="https://www.learnbayesstats.com/">https://www.learnbayesstats.com/ </a>

### Online learning material

The research group of Rens van de Schoot (Utrecht University) publishes a lot on Bayesian statistics. They also developed a summer school. Their materials are also openly available at (you will notice how their way of sharing materials has inspired me :-))  

<a href="https://utrechtuniversity.github.io/BayesianEstimation/#quick-overview">https://utrechtuniversity.github.io/BayesianEstimation/#quick-overview </a>

### My website

When I find the time I write short posts about (Bayesian) statistics. Some of the topics touched upon in the workshop are also documented in these posts, where I try to explain certain concepts or workflows. These posts also contain the necessary code!

<a href="https://sdemaeyer.quarto.pub/posts.html">https://sdemaeyer.quarto.pub/posts.html</a>

### Some example papers

Here some references to articles reporting on Bayesian analyses. 

Gijsen, M., Catrysse, L., De Maeyer, S., & Gijbels, D. (2024). Mapping cognitive processes in video-based learning by combining trace and think-aloud data. Learning and Instruction, 90, 101851. <a href="https://doi.org/10.1016/j.learninstruc.2023.101851" target="blank">https://doi.org/10.1016/j.learninstruc.2023.101851 </a>

Roeser, J., De Maeyer, S., Leijten, M., & Van Waes, L. (2021). Modelling typing disfluencies as finite mixture process. Reading and Writing. <a href="https://doi.org/10.1007/s11145-021-10203-z" target="blank"> https://doi.org/10.1007/s11145-021-10203-z </a>



### Article on Bayesian Evidence Interval

During the course I mentioned a paper that criticises the ROPE + HDI rule and proposes an alternative for making decisions on hypotheses in the Bayesian realm. This is the reference:  

Kelter, R. (2022), The evidence interval and the Bayesian evidence value: On a unified theory for Bayesian hypothesis testing and interval estimation. Br J Math Stat Psychol, 75: 550-592.  
<a href="https://bpspsychub.onlinelibrary.wiley.com/doi/full/10.1111/bmsp.12267" target="blank"> https://doi.org/10.1111/bmsp.12267 </a>